[package]
name = "webterm-shared"
version.workspace = true
edition.workspace = true

[dependencies]
dashmap = "6.1.0"
flatbuffers = "24.3.25"
rand = "0.8.5"
tokio = { version = "1.41.1", features = ["full"] }
tracing = "0.1.40"
futures = "0.3.31"
tokio-tungstenite = "0.24.0"
