name: Release-plz Release w/ Binaries

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main
  # TODO: REMOVE AFTER TESTING
  pull_request:

jobs:
  upload-binaries:
    name: Upload Binaries

    strategy:
      matrix:
        release:
          - package_name: webterm-agent
            version: 0.2.0
            tag: webterm-agent-v0.2.0
          - package_name: webterm-relay
            version: 0.2.0
            tag: webterm-relay-v0.2.0
        include:
          - release.package_name: webterm-agent
            target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-24.04

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Set environment
        id: set-env
        run: |
          PACKAGE_NAME="${{ matrix.release.package_name }}"
          VERSION="${{ matrix.release.version }}"
          TAG_NAME="${{ matrix.release.tag }}"

          echo "PACKAGE_NAME=${PACKAGE_NAME}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          echo "TARGET=${{ matrix.target }}" >> $GITHUB_ENV

      - name: Debug environment
        run: |
          echo "Package name: ${{ env.PACKAGE_NAME }}"
          echo "Version:      ${{ env.VERSION }}"
          echo "Tag:          ${{ env.TAG_NAME }}"
          echo "Ref:          ${{ env.GITHUB_REF }}"
          echo "Target:       ${{ env.TARGET }}"

      - name: Upload Rust Binary to GitHub Release
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: ${{ env.PACKAGE_NAME }}
          target: ${{ env.TARGET }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: refs/tags/${{ env.TAG_NAME }}
